config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check
  root 'dashboard#index'

  resources :authors do
    collection do
      get 'new_modal'
    end
  end

  resources :entries
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
# frozen_string_literal: true

class Author < ApplicationRecord
  include Searchable

  has_many :entries, through: :authors_entries
  validates :first_name, presence: true, unless: ->(author) { author.last_name.present? }
  validates :last_name, presence: true, unless: ->(author) { author.first_name.present? }
end

app/models/concerns/searchable.rb
# frozen_string_literal: true

module Searchable
  extend ActiveSupport::Concern

  class_methods do
    def starts_with(column, query)
      where("#{column} LIKE ?", "#{search_query(query)}%")
    end

    private

    def search_query(query)
      sanitize_sql_like(query.downcase)
    end
  end
end

app/models/entry.rb
# frozen_string_literal: true

class Entry < ApplicationRecord
  include Searchable

  has_many :authors, through: :authors_entries
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/authors_controller.rb
# frozen_string_literal: true

class AuthorsController < ApplicationController
  def create
    @author = Author.new(author_params)
    if @author.save
      flash.now[:notice] = t('authors.create_success')
      render turbo_stream: [
        turbo_stream.update('new_author_modal', partial: 'new_modal_link'),
        turbo_stream.update('notices', partial: 'shared/notices')
      ]
    else
      render :new_modal, status: :unprocessable_entity
    end
  end

  def new_modal
    @author = Author.new
  end

  def author_params
    params.expect(author: %i[first_name last_name distinction])
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  def index; end
end

app/controllers/entries_controller.rb
# frozen_string_literal: true

class EntriesController < ApplicationController
  def new
    @entry = Entry.new
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def notice_class(type)
    case type
    when 'notice'
      'success'
    when 'alert'
      'danger'
    else
      'primary'
    end
  end
end

app/helpers/authors_helper.rb
# frozen_string_literal: true

module AuthorsHelper
end

app/helpers/entries_helper.rb
# frozen_string_literal: true

module EntriesHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/authors/_form.html.slim
#author-modal-form.modal.fade[tabindex="-1" aria-labelledby="author-modal-label" aria-hidden="true"]
  .modal-dialog
    .modal-content
      .modal-header
        h1#author-modal-label.modal-title.fs-5
          = t('global.new_record', record_name: 'author')
        button.btn-close[type="button" data-bs-dismiss="modal" aria-label="Close"]
      .modal-body
        - if @author.errors.any?
          = render 'shared/record_errors', record: @author
        = form_with model: @author, local: true do |form|
          .mb-3
            = form.label :last_name, class: 'form-label'
            = form.text_field :last_name, class: 'form-control'
          .mb-3
            = form.label :first_name, class: 'form-label'
            = form.text_field :first_name, class: 'form-control'
          .mb-3
            = form.label :distinction, class: 'form-label'
            = form.text_field :distinction, class: 'form-control'
          .modal-footer
            = form.submit 'Save', class: 'btn btn-primary'
            button.btn.btn-secondary[type="button" data-bs-dismiss="modal"]
              | Close

app/views/authors/_new_modal_link.html.slim
= turbo_frame_tag 'new_author_modal' do
  = link_to 'New author', new_modal_authors_path, { class: 'btn btn-link text-end pb-2 ps-2 pt-1 border-0' }

app/views/authors/new_modal.html.slim
= turbo_frame_tag 'new_author_modal' do
  = link_to 'New author', new_modal_authors_path, { class: 'btn btn-link text-end pb-2 pt-1 border-0' }
  div[data-controller='authors-modal', data-action="turbo:submit-end->authors-modal#submitEnd"]
    = render 'form', author: @author

app/views/entries/_form.html.slim
- if @entry.errors.any?
  = render 'shared/record_errors', record: @entry
= form_with model: @entry, html: { class: 'g-3' } do |form|
  .col-6
    label.form-label.mb-0.pb-2.pt-1
      | Author
    = turbo_frame_tag 'new_author_modal'
      = link_to 'New author', new_modal_authors_path, { class: 'btn btn-link text-end pb-2 pt-1 border-0' }
  .col-6
    input.form-control[type="text_area" rows="3"]
  .col-12
    label.form-label
      | Full Title
    textarea.form-control[type="text_area" rows="3"]
  .text-center
    button.btn.btn-primary[type="submit"]
      | Submit
    button.btn.btn-secondary[type="reset"]
      | Reset

app/views/entries/new.html.slim
.col-lg-11.col-md-12
  .card
    .card-body
      h5.card-title.pt-2.pb-3
        = t('global.new_record', record_name: 'Entry')
      = render 'form'

app/views/layouts/_footer.html.slim
footer.small.pt-4.mt-auto
  .copyright
    | &copy; 
    = t('global.copyright')
  .credits.pt-2.pb-4
    = t('global.website_cta')
    a[href="#{t('global.website_link')}"]
      = t('global.website_link')

app/views/layouts/_head.html.slim
head
  title
    = t('title')
  meta[name="viewport" content="width=device-width, initial-scale=1"]
  meta[name='apple-mobile-web-app-capable' content='yes']
  meta[name='mobile-web-app-capable' content='yes']
  = csrf_meta_tags
  = csp_meta_tag
  = yield :head
  link[rel='icon' href='/icon.png' type='image/png']
  link[rel='icon' href='/icon.svg' type='image/svg+xml']
  link[rel='apple-touch-icon' href='/icon.png']
  = stylesheet_link_tag :application
  = javascript_importmap_tags

app/views/layouts/application.html.slim
doctype html
html
  = render 'layouts/head'
  body.d-flex.flex-column.min-vh-100
    = render 'layouts/navigation/header'
    = render 'layouts/navigation/sidenav'
    main
      #notices
        = render 'shared/notices'
      = yield
    = render 'layouts/footer'

app/views/layouts/navigation/_header.html.slim
header.navbar.header.fixed-top.d-flex.align-items-center
  .d-flex.align-items-center.justify-content-between
    a.logo.d-flex.align-items-center
      i.bi.bi-book
      span.d-none.d-lg-block
        = t('title')
  nav.header-nav.ms-auto.align-items-center.my-auto
    ul.navbar-nav.mr-auto
      li.nav-item.d-block.pe-4
        i.bi.bi-list.nav-icon.toggle-sidebar-btn

app/views/layouts/navigation/_sidenav.html.slim
aside.sidebar
  ul#sidebar-nav.sidebar-nav
    li.nav-item
      a.nav-link[href="#{new_entry_path}"]
        i.bi.bi-file-earmark-plus
        span
          = t('global.new_record', record_name: 'entry')

app/views/shared/_notices.html.slim
- flash.each do |key, message|
  - alert_class = notice_class(key)
  = content_tag :div, class: "alert alert-#{alert_class} alert-dismissible fade show col-lg-11 col-md-12" do
    = message
    button.btn-close[type="button" data-bs-dismiss="alert" aria-label="Close"]

app/views/shared/_record_errors.html.slim
.alert.alert-danger.alert-dismissible
  h6.alert-heading
    = t('errors.record.list',
        error_pluralized: pluralize(record.errors.count, 'error'),
        record_name: record.class.name.downcase)
  ul.mb-0
    - record.errors.map do |error|
      li
        = error.full_message
  button.btn-close[type='button' data-bs-dismiss='alert' aria-label='Close']